import type { Metadata } from "next";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"
import Script from "next/script";


export const metadata: Metadata = {
  title: "Charts - ERR0R 404",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=equal" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Gabarito:wght@900&family=Saira+Stencil+One&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Funnel+Sans:wght@800&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Protest+Guerrilla&display=swap" />
        <Script src="https://telegram.org/js/telegram-web-app.js?56" strategy="beforeInteractive"/>
      </head>
      <body className="h-full w-full flex justify-center bg-[var(--tg-theme-bg-color)] no-scrollbar">
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
